#!/usr/bin/env Rscript
# Knit vignettes/<name>.Rmd.orig -> vignettes/<name>.Rmd, CORRECTLY.
#
# Why this exists: knitr writes figures RELATIVE TO THE WORKING DIRECTORY. Running
#
#     Rscript -e 'knitr::knit("vignettes/x.Rmd.orig", output="vignettes/x.Rmd")'
#
# from the package root therefore writes figures to <root>/x_files/figure-html/
# and leaves the real vignettes/x_files/ figures STALE. The knitted .Rmd points at
# the stale images, dev/preview-vignette.R embeds the stale images, and nothing
# errors. (2026-08-06: this happened to all four vignettes and was only caught
# because the maintainer asked whether the figures had been regenerated.)
#
# This script sets the working directory to vignettes/ so figures land where the
# .Rmd expects them, and then PRINTS THE FIGURE TIMESTAMPS IT WROTE -- so "the
# figures were regenerated" is something you can see, not something to be assumed.
#
# It does NOT render HTML. Preview separately, after this:
#     Rscript dev/preview-vignette.R <name>
#
# Usage (from the package root):
#   Rscript dev/knit-vignette.R mode-analysis
#   Rscript dev/knit-vignette.R                 # every vignettes/*.Rmd.orig
#
# NOTE: `library(msamodel)` in a vignette loads the INSTALLED package. If the
# vignette exercises working-tree changes, run devtools::install() FIRST.

args <- commandArgs(trailingOnly = TRUE)

if (!dir.exists("vignettes")) {
  stop("Run this from the package root (no vignettes/ directory here).")
}

if (length(args) >= 1) {
  names <- sub("\\.Rmd(\\.orig)?$", "", basename(args))
} else {
  origs <- list.files("vignettes", pattern = "\\.Rmd\\.orig$")
  names <- sub("\\.Rmd\\.orig$", "", origs)
}
if (length(names) == 0) stop("No vignettes/*.Rmd.orig found.")

# Record figure state BEFORE, so "regenerated" is provable rather than assumed.
figure_state <- function(name) {
  d <- file.path("vignettes", paste0(name, "_files"), "figure-html")
  if (!dir.exists(d)) return(data.frame(file = character(), mtime = character()))
  fs <- list.files(d, full.names = TRUE)
  if (length(fs) == 0) return(data.frame(file = character(), mtime = character()))
  data.frame(file = basename(fs), mtime = format(file.info(fs)$mtime),
             stringsAsFactors = FALSE)
}

before <- stats::setNames(lapply(names, figure_state), names)

knit_one <- function(name) {
  orig <- paste0(name, ".Rmd.orig")
  if (!file.exists(file.path("vignettes", orig))) {
    stop("No such source: vignettes/", orig)
  }
  # THE POINT OF THIS SCRIPT: knit with the wd inside vignettes/, so figure paths
  # resolve to vignettes/<name>_files/ exactly as the shipped .Rmd references them.
  old <- setwd("vignettes")
  on.exit(setwd(old), add = TRUE)
  knitr::knit(orig, output = paste0(name, ".Rmd"), quiet = TRUE)
  message("knitted: vignettes/", name, ".Rmd")
}

invisible(lapply(names, knit_one))

# ---- Evidence: what actually changed on disk -------------------------------
cat("\n================ FIGURES WRITTEN ================\n")
stale <- character()
for (name in names) {
  after <- figure_state(name)
  cat("\n", name, ":\n", sep = "")
  if (nrow(after) == 0) {
    cat("   (no figures -- vignette produces none)\n")
    next
  }
  b <- before[[name]]
  for (i in seq_len(nrow(after))) {
    f <- after$file[i]
    was <- b$mtime[match(f, b$file)]
    changed <- is.na(was) || !identical(was, after$mtime[i])
    cat(sprintf("   %-40s %s  %s\n", f, after$mtime[i],
                if (changed) "REGENERATED" else "*** UNCHANGED ***"))
    if (!changed) stale <- c(stale, paste0(name, "/", f))
  }
}

cat("\n================================================\n")
if (length(stale)) {
  cat("WARNING:", length(stale), "figure(s) were NOT regenerated by this knit.\n")
  cat("Every figure should carry a fresh timestamp. If any did not, the knit did\n")
  cat("not write where the .Rmd points -- investigate before trusting a preview.\n")
} else {
  cat("All figures regenerated. Timestamps above are the evidence.\n")
}
cat("\nNext: Rscript dev/preview-vignette.R <name>   (then the USER approves the HTML)\n")
